### ISSUE TITLE
Error: An API error occurred: account_inactive

### ISSUE THREAD

**Issue by bennymeade** [trymbill/cypress-slack-video-upload-action#96]
We are getting error `account_inactive` after completing each step in: inputs > tokens

I can see from Slack docs the definition of error.
`account_inactive | Authentication token is for a deleted user or workspace when using a bot token.`

```
Run trymbill/cypress-slack-video-upload-action@v1.3.0
  with:
    token: xyx
    channels: cypress-results
/usr/bin/docker exec  763dc492a6xxxxxxxxxxxxxxxxx3b0d704a5e9026c42356 sh -c "cat /etc/*release | grep ^ID"
Error: An API error occurred: account_inactive
```

In your steps you say add permissions: do you mean add Bot Token Scopes permissions and leave User Token Scopes 
 blank?

Also the permission names do not match the names in your steps, can you confirm if what I selected is correct for Bot Token Scopes?

![image](https://user-images.githubusercontent.com/1033474/116709252-c9458400-a9d0-11eb-91e0-937e7ff02752.png)

![image](https://user-images.githubusercontent.com/1033474/116709426-f09c5100-a9d0-11eb-8b39-0efe859ad0f4.png)

**Comment by bennymeade** [comment]
I got this working today. My Bot Token Scopes are:
**chat:write
files:write**

- Originally I was hardcoding my bot token into the workflow rather than using GH secret (cutting corners). Do use **token: ${{ secrets.SLACK_TOKEN }}**
- Also to add the app to my Slack channel, just use **@AppName**, no need for /invite <bot-name>. Once I tidied these up the package works great.

This is the only package I found that actually posts the screenshots and videos into Slack, every other package just links back to the (Mochawesome) gh-pages assets folder in git repo. 

Well done to the author 👏 also I recommend you update the README token steps.

Here is an example of my Slack:
![image](https://user-images.githubusercontent.com/1033474/116819916-afdc3d80-ab72-11eb-8a5b-700557f7b965.png)

**Comment by trymbill** [comment]
Sorry for the late response, been AFK for a few days. Sorry for the confusion, glad you got it working, and thanks for the detailed information! I'll update the README so that nobody else has to jump through all those hoops.

Thanks again!
